### ISSUE TITLE
To-Do List Before AetherMC-snapshot.3

### ISSUE THREAD

**Issue by Outspending** [Outspending/AetherMC#1]
- [x] Finish ParticleUtils
- [x] Add Single Particle Effects
- [x] Player Writer (PlayerData, last location, is opped, ect)
- [x] More Region Constructors
- [x] Make ParticleDisplay editable (so you dont have to create a new instance every time ex. Looping)
- [x] More methods to Aether class
- [x] Fix .stripColors() method in new ChatColor class
