### ISSUE TITLE
To-Do List for AetherMC-snapshot.4

### ISSUE THREAD

**Issue by Outspending** [Outspending/AetherMC#2]
Snapshot.4 is a pretty big update. I'm adding many new features to the API to get it ready for a public release. This update will take a while, i would recommend you waiting for this to come out before you mess with aether's API since it isn't fully stable yet. This update is made to fix and add to the API to make it more user friendly and more modern.

## Features 🎉
- [ ] Rewrite Plugin System
- [ ] Add Plugin Libraries (ex. ./libraries)
- [ ] Make /plugins actually work
- [ ] Fully release API (For developers testing new API)
- [x] Plugin Algorithm (5-20ms to sort 52 plugins)
- [x] Blockstate handler
- [x] Implement Blockstates Correctly
- [x] Add Every Blockstate
- [x] Updated Logger
- [ ] Settings file
- [ ] EULA Confirmation when starting your server for the first time (This will be improved from spigot's version, you will be able to accept it in console without having to edit the eula.yml file)
- [ ] Experimental Features (Settings)
- [ ] Bug fixes
- [x] NumberUtils (format, and regex)
- [ ] Add new events
- [ ] Check Scoreboard API and Change If Needed
- [ ] Check Advancements API and Change If Needed
- [ ] Yaml Support (Json, and Toml support later)
- [ ] Chest Support

ETA: N/A
