### ISSUE TITLE
To-Do List for snapshot.7

### ISSUE THREAD

**Issue by Outspending** [Outspending/AetherMC#5]
The snapshot is all about GUI's. I'm planning on adding an easy GUI API for everyone to use. This also includes some Sign features using packets, ect

- [ ] GUI Builder
- [ ] GUI Slots
- [ ] Support Every Type Of Inventory
- [ ] Include a Sign Builder
- [ ] Get Text on a Line of a Sign
- [ ] GUI Cache (Caching GUI's so you dont have to create one everytime someone uses a command or an event)
